### PR TITLE
Rewrites to gatsby

### PR DESCRIPTION
**Pull request by imcodingideas**
Closes https://github.com/DetroitJS/detroitjs-com/issues/40

### CODE REVIEW

**Comment by imcodingideas** [comment]
@sixlive travis ci is failing for something else. Please let me know your feedback.

(node:3870) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ ./node_modules/.bin/eslint /src/components/*.js /src/components/pages/*.js

**Comment by sixlive** [comment]
Looks like there is an issue with eslint, would you mind removing eslint and setting up prettier?

**Comment by imcodingideas** [comment]
@sixlive sure, I can do that tomorrow at the latest. We're talking about the test command right?

**Comment by sixlive** [comment]
Well style formatting for the entire project as well as the Travis test.

No rush

**Comment by imcodingideas** [comment]
@sixlive I went ahead and setup husky for precommit stuff. This will run prettier. I've also removed .eslint per your request.

**Comment by sixlive** [comment]
DANG! Great work. 

When running the `build` command I'm getting an error. Can you look into this?

```bash
  Error: component---src-pages-index-js-deed973326ee9baf6a54.js from UglifyJs
  SyntaxError: Unexpected token operator «*», expected punc «(» [component---src-pages-index-js-deed973326ee9baf6a54.js:7658,42]
```

**Comment by imcodingideas** [comment]
Sure, let me figure out whats going on with the build. I haven't tired.

**Comment by imcodingideas** [comment]
@sixlive I was able to fix it. It looks like there is an issue with async componentDidMount() so I had to use a babel plugin to resolve the build issue.

**Pull request merged**
