### PR TITLE
WIP: Add Blog

### PR DESCRIPTION
**Pull request by sixlive**
Demo blog post that you should be able to access via `/blog/{post-slug}`. Content should be added to the content directory using the following pattern: `/content/{post-slug}.md`.

* Merges in work from mob code meetup with some cleanup/fixes
* Attempts to fix a bug with styled components and the circuits svg
* Fixes bug with trailing slash at end of blog path
* Fixes eslint errors
* Adds eslint helpers to package.json scripts

## Known Bugs
~* `Warning: Prop `className` did not match. Server: "sc-htpNat focPDi" Client: "sc-bdVaJa iPahWW"` – This looks to be a bug with SSR and styled components. I attempted to fix it but I didnt... Tried to work off [this example](https://github.com/zeit/next.js/tree/4.2.3/examples/with-styled-components).~

### CODE REVIEW

**Comment by sixlive** [comment]
For the `className` bug here is an issue on Nextjs that might be of help for whoever is trying to debug it... https://github.com/styled-components/styled-components/issues/1239

**Comment by seafoam6** [comment]
Should we wait until we have a blog post locked and loaded before we merge this?

**Comment by sixlive** [comment]
I would not merge this now hence `[WIP]`

**Comment by seafoam6** [comment]
I pushed up a fix for that lil' 🐛

**Pull request closed without merging**
